// Top 550+ US airports for SEO landing pages
// Includes major international, regional, general aviation, and executive airports
export const US_AIRPORTS = [
  // === TOP 50 BUSIEST BY PASSENGER TRAFFIC ===
  { icao: 'KATL', iata: 'ATL', name: 'Hartsfield-Jackson Atlanta International Airport', city: 'Atlanta', state: 'GA', type: 'International', lat: 33.6407, lon: -84.4277 },
  { icao: 'KLAX', iata: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', state: 'CA', type: 'International', lat: 33.9425, lon: -118.4081 },
  { icao: 'KORD', iata: 'ORD', name: "O'Hare International Airport", city: 'Chicago', state: 'IL', type: 'International', lat: 41.9742, lon: -87.9073 },
  { icao: 'KDFW', iata: 'DFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas', state: 'TX', type: 'International', lat: 32.8998, lon: -97.0403 },
  { icao: 'KDEN', iata: 'DEN', name: 'Denver International Airport', city: 'Denver', state: 'CO', type: 'International', lat: 39.8561, lon: -104.6737 },
  { icao: 'KJFK', iata: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', state: 'NY', type: 'International', lat: 40.6413, lon: -73.7781 },
  { icao: 'KSFO', iata: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', state: 'CA', type: 'International', lat: 37.6213, lon: -122.3790 },
  { icao: 'KSEA', iata: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle', state: 'WA', type: 'International', lat: 47.4502, lon: -122.3088 },
  { icao: 'KLAS', iata: 'LAS', name: 'Harry Reid International Airport', city: 'Las Vegas', state: 'NV', type: 'International', lat: 36.0840, lon: -115.1537 },
  { icao: 'KMCO', iata: 'MCO', name: 'Orlando International Airport', city: 'Orlando', state: 'FL', type: 'International', lat: 28.4312, lon: -81.3081 },
  { icao: 'KEWR', iata: 'EWR', name: 'Newark Liberty International Airport', city: 'Newark', state: 'NJ', type: 'International', lat: 40.6895, lon: -74.1745 },
  { icao: 'KCLT', iata: 'CLT', name: 'Charlotte Douglas International Airport', city: 'Charlotte', state: 'NC', type: 'International', lat: 35.2140, lon: -80.9431 },
  { icao: 'KPHX', iata: 'PHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', state: 'AZ', type: 'International', lat: 33.4373, lon: -112.0078 },
  { icao: 'KIAH', iata: 'IAH', name: 'George Bush Intercontinental Airport', city: 'Houston', state: 'TX', type: 'International', lat: 29.9902, lon: -95.3368 },
  { icao: 'KMIA', iata: 'MIA', name: 'Miami International Airport', city: 'Miami', state: 'FL', type: 'International', lat: 25.7959, lon: -80.2870 },
  { icao: 'KBOS', iata: 'BOS', name: 'Boston Logan International Airport', city: 'Boston', state: 'MA', type: 'International', lat: 42.3656, lon: -71.0096 },
  { icao: 'KMSP', iata: 'MSP', name: 'Minneapolis-Saint Paul International Airport', city: 'Minneapolis', state: 'MN', type: 'International', lat: 44.8848, lon: -93.2223 },
  { icao: 'KFLL', iata: 'FLL', name: 'Fort Lauderdale-Hollywood International Airport', city: 'Fort Lauderdale', state: 'FL', type: 'International', lat: 26.0742, lon: -80.1506 },
  { icao: 'KDTW', iata: 'DTW', name: 'Detroit Metropolitan Wayne County Airport', city: 'Detroit', state: 'MI', type: 'International', lat: 42.2124, lon: -83.3534 },
  { icao: 'KPHL', iata: 'PHL', name: 'Philadelphia International Airport', city: 'Philadelphia', state: 'PA', type: 'International', lat: 39.8721, lon: -75.2411 },
  { icao: 'KLGA', iata: 'LGA', name: 'LaGuardia Airport', city: 'New York', state: 'NY', type: 'International', lat: 40.7769, lon: -73.8740 },
  { icao: 'KBWI', iata: 'BWI', name: 'Baltimore/Washington International Airport', city: 'Baltimore', state: 'MD', type: 'International', lat: 39.1754, lon: -76.6684 },
  { icao: 'KSLC', iata: 'SLC', name: 'Salt Lake City International Airport', city: 'Salt Lake City', state: 'UT', type: 'International', lat: 40.7884, lon: -111.9778 },
  { icao: 'KIAD', iata: 'IAD', name: 'Washington Dulles International Airport', city: 'Dulles', state: 'VA', type: 'International', lat: 38.9531, lon: -77.4565 },
  { icao: 'KDCA', iata: 'DCA', name: 'Ronald Reagan Washington National Airport', city: 'Arlington', state: 'VA', type: 'International', lat: 38.8512, lon: -77.0402 },
  { icao: 'KSAN', iata: 'SAN', name: 'San Diego International Airport', city: 'San Diego', state: 'CA', type: 'International', lat: 32.7336, lon: -117.1897 },
  { icao: 'KTPA', iata: 'TPA', name: 'Tampa International Airport', city: 'Tampa', state: 'FL', type: 'International', lat: 27.9755, lon: -82.5332 },
  { icao: 'KPDX', iata: 'PDX', name: 'Portland International Airport', city: 'Portland', state: 'OR', type: 'International', lat: 45.5898, lon: -122.5951 },
  { icao: 'KMDW', iata: 'MDW', name: 'Chicago Midway International Airport', city: 'Chicago', state: 'IL', type: 'International', lat: 41.7868, lon: -87.7522 },
  { icao: 'KHNL', iata: 'HNL', name: 'Daniel K. Inouye International Airport', city: 'Honolulu', state: 'HI', type: 'International', lat: 21.3187, lon: -157.9225 },
  { icao: 'KSTL', iata: 'STL', name: 'St. Louis Lambert International Airport', city: 'St. Louis', state: 'MO', type: 'International', lat: 38.7487, lon: -90.3700 },
  { icao: 'KAUS', iata: 'AUS', name: 'Austin-Bergstrom International Airport', city: 'Austin', state: 'TX', type: 'International', lat: 30.1975, lon: -97.6664 },
  { icao: 'KBNA', iata: 'BNA', name: 'Nashville International Airport', city: 'Nashville', state: 'TN', type: 'International', lat: 36.1263, lon: -86.6774 },
  { icao: 'KHOU', iata: 'HOU', name: 'William P. Hobby Airport', city: 'Houston', state: 'TX', type: 'Regional', lat: 29.6454, lon: -95.2789 },
  { icao: 'KOAK', iata: 'OAK', name: 'Oakland International Airport', city: 'Oakland', state: 'CA', type: 'International', lat: 37.7213, lon: -122.2208 },
  { icao: 'KSJC', iata: 'SJC', name: 'San Jose International Airport', city: 'San Jose', state: 'CA', type: 'International', lat: 37.3626, lon: -121.9291 },
  { icao: 'KRDU', iata: 'RDU', name: 'Raleigh-Durham International Airport', city: 'Raleigh', state: 'NC', type: 'International', lat: 35.8776, lon: -78.7875 },
  { icao: 'KSAT', iata: 'SAT', name: 'San Antonio International Airport', city: 'San Antonio', state: 'TX', type: 'International', lat: 29.5337, lon: -98.4698 },
  { icao: 'KCLE', iata: 'CLE', name: 'Cleveland Hopkins International Airport', city: 'Cleveland', state: 'OH', type: 'International', lat: 41.4117, lon: -81.8498 },
  { icao: 'KPIT', iata: 'PIT', name: 'Pittsburgh International Airport', city: 'Pittsburgh', state: 'PA', type: 'International', lat: 40.4915, lon: -80.2329 },
  { icao: 'KIND', iata: 'IND', name: 'Indianapolis International Airport', city: 'Indianapolis', state: 'IN', type: 'International', lat: 39.7173, lon: -86.2944 },
  { icao: 'KCVG', iata: 'CVG', name: 'Cincinnati/Northern Kentucky International Airport', city: 'Cincinnati', state: 'OH', type: 'International', lat: 39.0488, lon: -84.6678 },
  { icao: 'KCMH', iata: 'CMH', name: 'John Glenn Columbus International Airport', city: 'Columbus', state: 'OH', type: 'International', lat: 39.9980, lon: -82.8919 },
  { icao: 'KMKE', iata: 'MKE', name: 'Milwaukee Mitchell International Airport', city: 'Milwaukee', state: 'WI', type: 'International', lat: 42.9472, lon: -87.8966 },
  { icao: 'KSMF', iata: 'SMF', name: 'Sacramento International Airport', city: 'Sacramento', state: 'CA', type: 'International', lat: 38.6954, lon: -121.5908 },
  { icao: 'KMCI', iata: 'MCI', name: 'Kansas City International Airport', city: 'Kansas City', state: 'MO', type: 'International', lat: 39.2976, lon: -94.7139 },
  { icao: 'KRNO', iata: 'RNO', name: 'Reno-Tahoe International Airport', city: 'Reno', state: 'NV', type: 'International', lat: 39.4991, lon: -119.7681 },
  { icao: 'KRSW', iata: 'RSW', name: 'Southwest Florida International Airport', city: 'Fort Myers', state: 'FL', type: 'International', lat: 26.5362, lon: -81.7552 },
  { icao: 'KANC', iata: 'ANC', name: 'Ted Stevens Anchorage International Airport', city: 'Anchorage', state: 'AK', type: 'International', lat: 61.1744, lon: -149.9964 },
  { icao: 'KSNA', iata: 'SNA', name: 'John Wayne Airport', city: 'Santa Ana', state: 'CA', type: 'Regional', lat: 33.6757, lon: -117.8678 },
  // === MAJOR BUSINESS AVIATION / EXECUTIVE AIRPORTS ===
  { icao: 'KTEB', iata: 'TEB', name: 'Teterboro Airport', city: 'Teterboro', state: 'NJ', type: 'Executive', lat: 40.8501, lon: -74.0608 },
  { icao: 'KVNY', iata: 'VNY', name: 'Van Nuys Airport', city: 'Van Nuys', state: 'CA', type: 'General Aviation', lat: 34.2098, lon: -118.4890 },
  { icao: 'KSDL', iata: 'SDL', name: 'Scottsdale Airport', city: 'Scottsdale', state: 'AZ', type: 'Executive', lat: 33.6229, lon: -111.9105 },
  { icao: 'KPBI', iata: 'PBI', name: 'Palm Beach International Airport', city: 'West Palm Beach', state: 'FL', type: 'International', lat: 26.6832, lon: -80.0956 },
  { icao: 'KBED', iata: 'BED', name: 'Laurence G. Hanscom Field', city: 'Bedford', state: 'MA', type: 'Executive', lat: 42.4700, lon: -71.2890 },
  { icao: 'KFRG', iata: 'FRG', name: 'Republic Airport', city: 'Farmingdale', state: 'NY', type: 'General Aviation', lat: 40.7288, lon: -73.4134 },
  { icao: 'KHPN', iata: 'HPN', name: 'Westchester County Airport', city: 'White Plains', state: 'NY', type: 'Executive', lat: 41.0670, lon: -73.7076 },
  { icao: 'KBFI', iata: 'BFI', name: 'Boeing Field/King County International Airport', city: 'Seattle', state: 'WA', type: 'Executive', lat: 47.5300, lon: -122.3020 },
  { icao: 'KAPA', iata: 'APA', name: 'Centennial Airport', city: 'Englewood', state: 'CO', type: 'Executive', lat: 39.5701, lon: -104.8493 },
  { icao: 'KOPF', iata: 'OPF', name: 'Miami-Opa Locka Executive Airport', city: 'Opa-locka', state: 'FL', type: 'Executive', lat: 25.9070, lon: -80.2784 },
  { icao: 'KFXE', iata: 'FXE', name: 'Fort Lauderdale Executive Airport', city: 'Fort Lauderdale', state: 'FL', type: 'Executive', lat: 26.1973, lon: -80.1707 },
  { icao: 'KDAL', iata: 'DAL', name: 'Dallas Love Field', city: 'Dallas', state: 'TX', type: 'Regional', lat: 32.8471, lon: -96.8518 },
  { icao: 'KADS', iata: 'ADS', name: 'Addison Airport', city: 'Addison', state: 'TX', type: 'Executive', lat: 32.9686, lon: -96.8364 },
  { icao: 'KDPA', iata: 'DPA', name: 'DuPage Airport', city: 'West Chicago', state: 'IL', type: 'Executive', lat: 41.9078, lon: -88.2486 },
  { icao: 'KPWK', iata: 'PWK', name: 'Chicago Executive Airport', city: 'Wheeling', state: 'IL', type: 'Executive', lat: 42.1142, lon: -87.9015 },
  { icao: 'KPTK', iata: 'PTK', name: 'Oakland County International Airport', city: 'Waterford', state: 'MI', type: 'Executive', lat: 42.6655, lon: -83.4185 },
  { icao: 'KPDK', iata: 'PDK', name: 'DeKalb-Peachtree Airport', city: 'Atlanta', state: 'GA', type: 'Executive', lat: 33.8756, lon: -84.3020 },
  { icao: 'KMMU', iata: 'MMU', name: 'Morristown Municipal Airport', city: 'Morristown', state: 'NJ', type: 'Executive', lat: 40.7994, lon: -74.4149 },
  { icao: 'KORL', iata: 'ORL', name: 'Orlando Executive Airport', city: 'Orlando', state: 'FL', type: 'Executive', lat: 28.5455, lon: -81.3329 },
  { icao: 'KBJC', iata: 'BJC', name: 'Rocky Mountain Metropolitan Airport', city: 'Broomfield', state: 'CO', type: 'Executive', lat: 39.9088, lon: -105.1172 },
  { icao: 'KSUS', iata: 'SUS', name: 'Spirit of St. Louis Airport', city: 'Chesterfield', state: 'MO', type: 'Executive', lat: 38.6621, lon: -90.6524 },
  { icao: 'KFCM', iata: 'FCM', name: 'Flying Cloud Airport', city: 'Eden Prairie', state: 'MN', type: 'Executive', lat: 44.8272, lon: -93.4572 },
  { icao: 'KSGR', iata: 'SGR', name: 'Sugar Land Regional Airport', city: 'Sugar Land', state: 'TX', type: 'Executive', lat: 29.6223, lon: -95.6565 },
  { icao: 'KFTW', iata: 'FTW', name: 'Fort Worth Meacham International Airport', city: 'Fort Worth', state: 'TX', type: 'Executive', lat: 32.8198, lon: -97.3624 },
  { icao: 'KBCT', iata: 'BCT', name: 'Boca Raton Airport', city: 'Boca Raton', state: 'FL', type: 'Executive', lat: 26.3785, lon: -80.1077 },
  { icao: 'KTMB', iata: 'TMB', name: 'Miami Executive Airport', city: 'Miami', state: 'FL', type: 'Executive', lat: 25.6479, lon: -80.4328 },
  { icao: 'KAGC', iata: 'AGC', name: 'Allegheny County Airport', city: 'Pittsburgh', state: 'PA', type: 'Executive', lat: 40.3544, lon: -79.9302 },
  { icao: 'KHEF', iata: 'MNZ', name: 'Manassas Regional Airport', city: 'Manassas', state: 'VA', type: 'Executive', lat: 38.7214, lon: -77.5155 },
  { icao: 'KJYO', iata: 'JYO', name: 'Leesburg Executive Airport', city: 'Leesburg', state: 'VA', type: 'Executive', lat: 39.0780, lon: -77.5575 },
  { icao: 'KHND', iata: 'HND', name: 'Henderson Executive Airport', city: 'Henderson', state: 'NV', type: 'Executive', lat: 35.9728, lon: -115.1344 },
  { icao: 'KSTP', iata: 'STP', name: 'St. Paul Downtown Airport', city: 'St. Paul', state: 'MN', type: 'Executive', lat: 44.9345, lon: -93.0600 },
  { icao: 'KEDC', iata: 'EDC', name: 'Austin Executive Airport', city: 'Austin', state: 'TX', type: 'Executive', lat: 30.3985, lon: -97.5664 },
  { icao: 'KCXO', iata: 'CXO', name: 'Lone Star Executive Airport', city: 'Conroe', state: 'TX', type: 'Executive', lat: 30.3518, lon: -95.4146 },
  { icao: 'KHWD', iata: 'HWD', name: 'Hayward Executive Airport', city: 'Hayward', state: 'CA', type: 'Executive', lat: 37.6592, lon: -122.1222 },
  { icao: 'KMYF', iata: 'MYF', name: 'Montgomery-Gibbs Executive Airport', city: 'San Diego', state: 'CA', type: 'Executive', lat: 32.8157, lon: -117.1397 },
  { icao: 'KNEW', iata: 'NEW', name: 'Lakefront Airport', city: 'New Orleans', state: 'LA', type: 'Executive', lat: 30.0424, lon: -90.0283 },
  // === REGIONAL COMMERCIAL AIRPORTS ===
  { icao: 'KABQ', iata: 'ABQ', name: 'Albuquerque International Sunport', city: 'Albuquerque', state: 'NM', type: 'International', lat: 35.0402, lon: -106.6091 },
  { icao: 'KBDL', iata: 'BDL', name: 'Bradley International Airport', city: 'Hartford', state: 'CT', type: 'International', lat: 41.9389, lon: -72.6832 },
  { icao: 'KBHM', iata: 'BHM', name: 'Birmingham-Shuttlesworth International Airport', city: 'Birmingham', state: 'AL', type: 'International', lat: 33.5629, lon: -86.7535 },
  { icao: 'KBOI', iata: 'BOI', name: 'Boise Airport', city: 'Boise', state: 'ID', type: 'Regional', lat: 43.5644, lon: -116.2228 },
  { icao: 'KBUF', iata: 'BUF', name: 'Buffalo Niagara International Airport', city: 'Buffalo', state: 'NY', type: 'International', lat: 42.9405, lon: -78.7322 },
  { icao: 'KCHS', iata: 'CHS', name: 'Charleston International Airport', city: 'Charleston', state: 'SC', type: 'International', lat: 32.8986, lon: -80.0405 },
  { icao: 'KCOS', iata: 'COS', name: 'Colorado Springs Airport', city: 'Colorado Springs', state: 'CO', type: 'Regional', lat: 38.8058, lon: -104.7007 },
  { icao: 'KDAY', iata: 'DAY', name: 'James M. Cox Dayton International Airport', city: 'Dayton', state: 'OH', type: 'International', lat: 39.9024, lon: -84.2194 },
  { icao: 'KDSM', iata: 'DSM', name: 'Des Moines International Airport', city: 'Des Moines', state: 'IA', type: 'International', lat: 41.5340, lon: -93.6631 },
  { icao: 'KELP', iata: 'ELP', name: 'El Paso International Airport', city: 'El Paso', state: 'TX', type: 'International', lat: 31.8072, lon: -106.3778 },
  { icao: 'KGSO', iata: 'GSO', name: 'Piedmont Triad International Airport', city: 'Greensboro', state: 'NC', type: 'International', lat: 36.0978, lon: -79.9373 },
  { icao: 'KGSP', iata: 'GSP', name: 'Greenville-Spartanburg International Airport', city: 'Greer', state: 'SC', type: 'International', lat: 34.8957, lon: -82.2189 },
  { icao: 'KICT', iata: 'ICT', name: 'Wichita Dwight D. Eisenhower National Airport', city: 'Wichita', state: 'KS', type: 'Regional', lat: 37.6499, lon: -97.4331 },
  { icao: 'KJAX', iata: 'JAX', name: 'Jacksonville International Airport', city: 'Jacksonville', state: 'FL', type: 'International', lat: 30.4941, lon: -81.6879 },
  { icao: 'KLIT', iata: 'LIT', name: 'Bill and Hillary Clinton National Airport', city: 'Little Rock', state: 'AR', type: 'Regional', lat: 34.7294, lon: -92.2243 },
  { icao: 'KMEM', iata: 'MEM', name: 'Memphis International Airport', city: 'Memphis', state: 'TN', type: 'International', lat: 35.0424, lon: -89.9767 },
  { icao: 'KMSY', iata: 'MSY', name: 'Louis Armstrong New Orleans International Airport', city: 'New Orleans', state: 'LA', type: 'International', lat: 29.9934, lon: -90.2580 },
  { icao: 'KOMA', iata: 'OMA', name: 'Eppley Airfield', city: 'Omaha', state: 'NE', type: 'Regional', lat: 41.3032, lon: -95.8941 },
  { icao: 'KONT', iata: 'ONT', name: 'Ontario International Airport', city: 'Ontario', state: 'CA', type: 'International', lat: 34.0560, lon: -117.6012 },
  { icao: 'KPVD', iata: 'PVD', name: 'T.F. Green International Airport', city: 'Providence', state: 'RI', type: 'International', lat: 41.7240, lon: -71.4283 },
  { icao: 'KRIC', iata: 'RIC', name: 'Richmond International Airport', city: 'Richmond', state: 'VA', type: 'International', lat: 37.5052, lon: -77.3197 },
  { icao: 'KSDF', iata: 'SDF', name: 'Louisville Muhammad Ali International Airport', city: 'Louisville', state: 'KY', type: 'International', lat: 38.1740, lon: -85.7360 },
  { icao: 'KSYR', iata: 'SYR', name: 'Syracuse Hancock International Airport', city: 'Syracuse', state: 'NY', type: 'International', lat: 43.1112, lon: -76.1063 },
  { icao: 'KTUL', iata: 'TUL', name: 'Tulsa International Airport', city: 'Tulsa', state: 'OK', type: 'International', lat: 36.1984, lon: -95.8881 },
  { icao: 'KTUS', iata: 'TUS', name: 'Tucson International Airport', city: 'Tucson', state: 'AZ', type: 'International', lat: 32.1161, lon: -110.9410 },
  { icao: 'KOKC', iata: 'OKC', name: 'Will Rogers World Airport', city: 'Oklahoma City', state: 'OK', type: 'International', lat: 35.3931, lon: -97.6007 },
  { icao: 'KORF', iata: 'ORF', name: 'Norfolk International Airport', city: 'Norfolk', state: 'VA', type: 'International', lat: 36.8946, lon: -76.2012 },
  { icao: 'KALB', iata: 'ALB', name: 'Albany International Airport', city: 'Albany', state: 'NY', type: 'International', lat: 42.7483, lon: -73.8029 },
  { icao: 'KGRR', iata: 'GRR', name: 'Gerald R. Ford International Airport', city: 'Grand Rapids', state: 'MI', type: 'International', lat: 42.8808, lon: -85.5228 },
  { icao: 'KSAV', iata: 'SAV', name: 'Savannah/Hilton Head International Airport', city: 'Savannah', state: 'GA', type: 'International', lat: 32.1276, lon: -81.2021 },
  { icao: 'KTYS', iata: 'TYS', name: 'McGhee Tyson Airport', city: 'Knoxville', state: 'TN', type: 'Regional', lat: 35.8109, lon: -83.9940 },
  { icao: 'KHSV', iata: 'HSV', name: 'Huntsville International Airport', city: 'Huntsville', state: 'AL', type: 'International', lat: 34.6372, lon: -86.7751 },
  { icao: 'KPSP', iata: 'PSP', name: 'Palm Springs International Airport', city: 'Palm Springs', state: 'CA', type: 'International', lat: 33.8303, lon: -116.5067 },
  { icao: 'KLEX', iata: 'LEX', name: 'Blue Grass Airport', city: 'Lexington', state: 'KY', type: 'Regional', lat: 38.0365, lon: -84.6059 },
  { icao: 'KMYR', iata: 'MYR', name: 'Myrtle Beach International Airport', city: 'Myrtle Beach', state: 'SC', type: 'International', lat: 33.6797, lon: -78.9283 },
  { icao: 'KPNS', iata: 'PNS', name: 'Pensacola International Airport', city: 'Pensacola', state: 'FL', type: 'International', lat: 30.4734, lon: -87.1866 },
  { icao: 'KSRQ', iata: 'SRQ', name: 'Sarasota/Bradenton International Airport', city: 'Sarasota', state: 'FL', type: 'International', lat: 27.3954, lon: -82.5544 },
  { icao: 'KGEG', iata: 'GEG', name: 'Spokane International Airport', city: 'Spokane', state: 'WA', type: 'International', lat: 47.6199, lon: -117.5338 },
  { icao: 'KBTV', iata: 'BTV', name: 'Burlington International Airport', city: 'Burlington', state: 'VT', type: 'International', lat: 44.4720, lon: -73.1533 },
  { icao: 'KMHT', iata: 'MHT', name: 'Manchester-Boston Regional Airport', city: 'Manchester', state: 'NH', type: 'Regional', lat: 42.9326, lon: -71.4357 },
  { icao: 'KBGR', iata: 'BGR', name: 'Bangor International Airport', city: 'Bangor', state: 'ME', type: 'International', lat: 44.8074, lon: -68.8281 },
  { icao: 'KPWM', iata: 'PWM', name: 'Portland International Jetport', city: 'Portland', state: 'ME', type: 'Regional', lat: 43.6462, lon: -70.3093 },
  { icao: 'KBUR', iata: 'BUR', name: 'Hollywood Burbank Airport', city: 'Burbank', state: 'CA', type: 'Regional', lat: 34.1975, lon: -118.3585 },
  // === MOUNTAIN WEST / SKI TOWNS ===
  { icao: 'KEGE', iata: 'EGE', name: 'Eagle County Regional Airport', city: 'Vail', state: 'CO', type: 'Regional', lat: 39.6426, lon: -106.9159 },
  { icao: 'KASE', iata: 'ASE', name: 'Aspen/Pitkin County Airport', city: 'Aspen', state: 'CO', type: 'Regional', lat: 39.2232, lon: -106.8689 },
  { icao: 'KGJT', iata: 'GJT', name: 'Grand Junction Regional Airport', city: 'Grand Junction', state: 'CO', type: 'Regional', lat: 39.1224, lon: -108.5267 },
  { icao: 'KGUC', iata: 'GUC', name: 'Gunnison-Crested Butte Regional Airport', city: 'Gunnison', state: 'CO', type: 'Regional', lat: 38.5339, lon: -106.9332 },
  { icao: 'KDRO', iata: 'DRO', name: 'Durango-La Plata County Airport', city: 'Durango', state: 'CO', type: 'Regional', lat: 37.1515, lon: -107.7538 },
  { icao: 'KMTJ', iata: 'MTJ', name: 'Montrose Regional Airport', city: 'Montrose', state: 'CO', type: 'Regional', lat: 38.5098, lon: -107.8942 },
  { icao: 'KHDN', iata: 'HDN', name: 'Yampa Valley Airport', city: 'Hayden', state: 'CO', type: 'Regional', lat: 40.4812, lon: -107.2177 },
  { icao: 'KJAC', iata: 'JAC', name: 'Jackson Hole Airport', city: 'Jackson', state: 'WY', type: 'Regional', lat: 43.6073, lon: -110.7378 },
  { icao: 'KSUN', iata: 'SUN', name: 'Friedman Memorial Airport', city: 'Hailey', state: 'ID', type: 'Regional', lat: 43.5044, lon: -114.2963 },
  { icao: 'KBZN', iata: 'BZN', name: 'Bozeman Yellowstone International Airport', city: 'Bozeman', state: 'MT', type: 'International', lat: 45.7775, lon: -111.1530 },
  { icao: 'KFCA', iata: 'FCA', name: 'Glacier Park International Airport', city: 'Kalispell', state: 'MT', type: 'Regional', lat: 48.3105, lon: -114.2560 },
  { icao: 'KMSO', iata: 'MSO', name: 'Missoula Montana Airport', city: 'Missoula', state: 'MT', type: 'Regional', lat: 46.9163, lon: -114.0906 },
  // === FLORIDA GA/REGIONAL ===
  { icao: 'KAPF', iata: 'APF', name: 'Naples Municipal Airport', city: 'Naples', state: 'FL', type: 'General Aviation', lat: 26.1526, lon: -81.7753 },
  { icao: 'KSFB', iata: 'SFB', name: 'Orlando Sanford International Airport', city: 'Sanford', state: 'FL', type: 'International', lat: 28.7776, lon: -81.2375 },
  { icao: 'KPIE', iata: 'PIE', name: 'St. Pete-Clearwater International Airport', city: 'St. Petersburg', state: 'FL', type: 'International', lat: 27.9102, lon: -82.6874 },
  { icao: 'KTLH', iata: 'TLH', name: 'Tallahassee International Airport', city: 'Tallahassee', state: 'FL', type: 'International', lat: 30.3965, lon: -84.3503 },
  { icao: 'KMLB', iata: 'MLB', name: 'Melbourne Orlando International Airport', city: 'Melbourne', state: 'FL', type: 'International', lat: 28.1028, lon: -80.6453 },
  { icao: 'KDAB', iata: 'DAB', name: 'Daytona Beach International Airport', city: 'Daytona Beach', state: 'FL', type: 'International', lat: 29.1799, lon: -81.0581 },
  { icao: 'KGNV', iata: 'GNV', name: 'Gainesville Regional Airport', city: 'Gainesville', state: 'FL', type: 'Regional', lat: 29.6901, lon: -82.2718 },
  { icao: 'KVPS', iata: 'VPS', name: 'Destin-Fort Walton Beach Airport', city: 'Fort Walton Beach', state: 'FL', type: 'Regional', lat: 30.4832, lon: -86.5254 },
  { icao: 'KECP', iata: 'ECP', name: 'Northwest Florida Beaches International Airport', city: 'Panama City Beach', state: 'FL', type: 'International', lat: 30.3580, lon: -85.7956 },
  { icao: 'KISM', iata: 'ISM', name: 'Kissimmee Gateway Airport', city: 'Kissimmee', state: 'FL', type: 'General Aviation', lat: 28.2898, lon: -81.4371 },
  { icao: 'KLAL', iata: 'LAL', name: 'Lakeland Linder International Airport', city: 'Lakeland', state: 'FL', type: 'International', lat: 27.9889, lon: -82.0186 },
  { icao: 'KFMY', iata: 'FMY', name: 'Page Field', city: 'Fort Myers', state: 'FL', type: 'General Aviation', lat: 26.5866, lon: -81.8633 },
  { icao: 'KVRB', iata: 'VRB', name: 'Vero Beach Regional Airport', city: 'Vero Beach', state: 'FL', type: 'General Aviation', lat: 27.6556, lon: -80.4179 },
  { icao: 'KSGJ', iata: 'SGJ', name: 'Northeast Florida Regional Airport', city: 'St. Augustine', state: 'FL', type: 'General Aviation', lat: 29.9592, lon: -81.3398 },
  { icao: 'KOCF', iata: 'OCF', name: 'Ocala International Airport', city: 'Ocala', state: 'FL', type: 'General Aviation', lat: 29.1717, lon: -82.2236 },
  { icao: 'KHWO', iata: 'HWO', name: 'North Perry Airport', city: 'Hollywood', state: 'FL', type: 'General Aviation', lat: 26.0012, lon: -80.2407 },
  { icao: 'KSPG', iata: 'SPG', name: 'Albert Whitted Airport', city: 'St. Petersburg', state: 'FL', type: 'General Aviation', lat: 27.7651, lon: -82.6270 },
  { icao: 'KFPR', iata: 'FPR', name: 'Treasure Coast International Airport', city: 'Fort Pierce', state: 'FL', type: 'General Aviation', lat: 27.4951, lon: -80.3683 },
  // === CALIFORNIA GA ===
  { icao: 'KSBA', iata: 'SBA', name: 'Santa Barbara Airport', city: 'Santa Barbara', state: 'CA', type: 'Regional', lat: 34.4262, lon: -119.8404 },
  { icao: 'KLGB', iata: 'LGB', name: 'Long Beach Airport', city: 'Long Beach', state: 'CA', type: 'Regional', lat: 33.8177, lon: -118.1516 },
  { icao: 'KFAT', iata: 'FAT', name: 'Fresno Yosemite International Airport', city: 'Fresno', state: 'CA', type: 'International', lat: 36.7762, lon: -119.7181 },
  { icao: 'KSBP', iata: 'SBP', name: 'San Luis Obispo County Regional Airport', city: 'San Luis Obispo', state: 'CA', type: 'Regional', lat: 35.2368, lon: -120.6424 },
  { icao: 'KSTS', iata: 'STS', name: 'Charles M. Schulz Sonoma County Airport', city: 'Santa Rosa', state: 'CA', type: 'Regional', lat: 38.5091, lon: -122.8128 },
  { icao: 'KCCR', iata: 'CCR', name: 'Buchanan Field Airport', city: 'Concord', state: 'CA', type: 'General Aviation', lat: 37.9897, lon: -122.0569 },
  { icao: 'KMRY', iata: 'MRY', name: 'Monterey Regional Airport', city: 'Monterey', state: 'CA', type: 'Regional', lat: 36.5870, lon: -121.8430 },
  { icao: 'KCRQ', iata: 'CRQ', name: 'McClellan-Palomar Airport', city: 'Carlsbad', state: 'CA', type: 'General Aviation', lat: 33.1283, lon: -117.2803 },
  { icao: 'KCMA', iata: 'CMA', name: 'Camarillo Airport', city: 'Camarillo', state: 'CA', type: 'General Aviation', lat: 34.2137, lon: -119.0943 },
  { icao: 'KBFL', iata: 'BFL', name: 'Meadows Field Airport', city: 'Bakersfield', state: 'CA', type: 'Regional', lat: 35.4336, lon: -119.0568 },
  { icao: 'KAPC', iata: 'APC', name: 'Napa County Airport', city: 'Napa', state: 'CA', type: 'General Aviation', lat: 38.2132, lon: -122.2807 },
  { icao: 'KPAO', iata: 'PAO', name: 'Palo Alto Airport', city: 'Palo Alto', state: 'CA', type: 'General Aviation', lat: 37.4611, lon: -122.1150 },
  { icao: 'KSEE', iata: 'SEE', name: 'Gillespie Field', city: 'El Cajon', state: 'CA', type: 'General Aviation', lat: 32.8262, lon: -116.9724 },
  { icao: 'KCNO', iata: 'CNO', name: 'Chino Airport', city: 'Chino', state: 'CA', type: 'General Aviation', lat: 33.9747, lon: -117.6368 },
  { icao: 'KFUL', iata: 'FUL', name: 'Fullerton Municipal Airport', city: 'Fullerton', state: 'CA', type: 'General Aviation', lat: 33.8720, lon: -117.9803 },
  { icao: 'KTOA', iata: 'TOA', name: 'Zamperini Field', city: 'Torrance', state: 'CA', type: 'General Aviation', lat: 33.8034, lon: -118.3396 },
  { icao: 'KRDD', iata: 'RDD', name: 'Redding Municipal Airport', city: 'Redding', state: 'CA', type: 'Regional', lat: 40.5090, lon: -122.2934 },
  { icao: 'KTRK', iata: 'TRK', name: 'Truckee Tahoe Airport', city: 'Truckee', state: 'CA', type: 'General Aviation', lat: 39.3200, lon: -120.1396 },
  // === ARIZONA ===
  { icao: 'KFFZ', iata: 'FFZ', name: 'Falcon Field', city: 'Mesa', state: 'AZ', type: 'General Aviation', lat: 33.4608, lon: -111.7282 },
  { icao: 'KIWA', iata: 'IWA', name: 'Phoenix-Mesa Gateway Airport', city: 'Mesa', state: 'AZ', type: 'Regional', lat: 33.3078, lon: -111.6556 },
  { icao: 'KDVT', iata: 'DVT', name: 'Phoenix Deer Valley Airport', city: 'Phoenix', state: 'AZ', type: 'General Aviation', lat: 33.6883, lon: -112.0833 },
  { icao: 'KFLG', iata: 'FLG', name: 'Flagstaff Pulliam Airport', city: 'Flagstaff', state: 'AZ', type: 'Regional', lat: 35.1385, lon: -111.6692 },
  { icao: 'KPRC', iata: 'PRC', name: 'Ernest A. Love Field', city: 'Prescott', state: 'AZ', type: 'General Aviation', lat: 34.6545, lon: -112.4196 },
  { icao: 'KGCN', iata: 'GCN', name: 'Grand Canyon National Park Airport', city: 'Grand Canyon', state: 'AZ', type: 'Regional', lat: 35.9524, lon: -112.1470 },
  // === PACIFIC NORTHWEST ===
  { icao: 'KPAE', iata: 'PAE', name: 'Snohomish County Airport (Paine Field)', city: 'Everett', state: 'WA', type: 'Regional', lat: 47.9063, lon: -122.2816 },
  { icao: 'KBLI', iata: 'BLI', name: 'Bellingham International Airport', city: 'Bellingham', state: 'WA', type: 'International', lat: 48.7928, lon: -122.5375 },
  { icao: 'KPSC', iata: 'PSC', name: 'Tri-Cities Airport', city: 'Pasco', state: 'WA', type: 'Regional', lat: 46.2647, lon: -119.1191 },
  { icao: 'KYKM', iata: 'YKM', name: 'Yakima Air Terminal', city: 'Yakima', state: 'WA', type: 'Regional', lat: 46.5682, lon: -120.5440 },
  { icao: 'KOLM', iata: 'OLM', name: 'Olympia Regional Airport', city: 'Olympia', state: 'WA', type: 'Regional', lat: 46.9694, lon: -122.9025 },
  { icao: 'KRDM', iata: 'RDM', name: 'Redmond Municipal Airport', city: 'Redmond', state: 'OR', type: 'Regional', lat: 44.2541, lon: -121.1500 },
  { icao: 'KEUG', iata: 'EUG', name: 'Eugene Airport', city: 'Eugene', state: 'OR', type: 'Regional', lat: 44.1246, lon: -123.2119 },
  { icao: 'KMFR', iata: 'MFR', name: 'Rogue Valley International-Medford Airport', city: 'Medford', state: 'OR', type: 'Regional', lat: 42.3742, lon: -122.8735 },
  { icao: 'KHIO', iata: 'HIO', name: 'Portland-Hillsboro Airport', city: 'Hillsboro', state: 'OR', type: 'General Aviation', lat: 45.5404, lon: -122.9498 },
  { icao: 'KSLE', iata: 'SLE', name: 'McNary Field', city: 'Salem', state: 'OR', type: 'Regional', lat: 44.9095, lon: -123.0032 },
  // === UTAH / NEVADA / IDAHO ===
  { icao: 'KSGU', iata: 'SGU', name: 'St. George Regional Airport', city: 'St. George', state: 'UT', type: 'Regional', lat: 37.0364, lon: -113.5103 },
  { icao: 'KPVU', iata: 'PVU', name: 'Provo Municipal Airport', city: 'Provo', state: 'UT', type: 'General Aviation', lat: 40.2192, lon: -111.7235 },
  { icao: 'KOGD', iata: 'OGD', name: 'Ogden-Hinckley Airport', city: 'Ogden', state: 'UT', type: 'General Aviation', lat: 41.1961, lon: -112.0122 },
  { icao: 'KVGT', iata: 'VGT', name: 'North Las Vegas Airport', city: 'Las Vegas', state: 'NV', type: 'General Aviation', lat: 36.2107, lon: -115.1944 },
  { icao: 'KIDA', iata: 'IDA', name: 'Idaho Falls Regional Airport', city: 'Idaho Falls', state: 'ID', type: 'Regional', lat: 43.5146, lon: -112.0708 },
  { icao: 'KTWF', iata: 'TWF', name: 'Magic Valley Regional Airport', city: 'Twin Falls', state: 'ID', type: 'Regional', lat: 42.4818, lon: -114.4877 },
  { icao: 'KLWS', iata: 'LWS', name: 'Lewiston-Nez Perce County Airport', city: 'Lewiston', state: 'ID', type: 'Regional', lat: 46.3745, lon: -117.0154 },
  // === MONTANA / WYOMING / DAKOTAS ===
  { icao: 'KBIL', iata: 'BIL', name: 'Billings Logan International Airport', city: 'Billings', state: 'MT', type: 'International', lat: 45.8077, lon: -108.5429 },
  { icao: 'KGTF', iata: 'GTF', name: 'Great Falls International Airport', city: 'Great Falls', state: 'MT', type: 'International', lat: 47.4820, lon: -111.3707 },
  { icao: 'KHLN', iata: 'HLN', name: 'Helena Regional Airport', city: 'Helena', state: 'MT', type: 'Regional', lat: 46.6068, lon: -111.9827 },
  { icao: 'KCPR', iata: 'CPR', name: 'Casper/Natrona County International Airport', city: 'Casper', state: 'WY', type: 'Regional', lat: 42.9080, lon: -106.4643 },
  { icao: 'KCYS', iata: 'CYS', name: 'Cheyenne Regional Airport', city: 'Cheyenne', state: 'WY', type: 'Regional', lat: 41.1557, lon: -104.8118 },
  { icao: 'KFSD', iata: 'FSD', name: 'Sioux Falls Regional Airport', city: 'Sioux Falls', state: 'SD', type: 'Regional', lat: 43.5820, lon: -96.7419 },
  { icao: 'KRAP', iata: 'RAP', name: 'Rapid City Regional Airport', city: 'Rapid City', state: 'SD', type: 'Regional', lat: 44.0453, lon: -103.0574 },
  { icao: 'KFAR', iata: 'FAR', name: 'Hector International Airport', city: 'Fargo', state: 'ND', type: 'International', lat: 46.9207, lon: -96.8158 },
  { icao: 'KBIS', iata: 'BIS', name: 'Bismarck Airport', city: 'Bismarck', state: 'ND', type: 'Regional', lat: 46.7727, lon: -100.7461 },
  { icao: 'KGFK', iata: 'GFK', name: 'Grand Forks International Airport', city: 'Grand Forks', state: 'ND', type: 'International', lat: 47.9493, lon: -97.1761 },
  { icao: 'KMOT', iata: 'MOT', name: 'Minot International Airport', city: 'Minot', state: 'ND', type: 'International', lat: 48.2594, lon: -101.2803 },
  // === MIDWEST ===
  { icao: 'KMSN', iata: 'MSN', name: 'Dane County Regional Airport', city: 'Madison', state: 'WI', type: 'Regional', lat: 43.1399, lon: -89.3375 },
  { icao: 'KGRB', iata: 'GRB', name: 'Green Bay Austin Straubel International Airport', city: 'Green Bay', state: 'WI', type: 'International', lat: 44.4851, lon: -88.1296 },
  { icao: 'KATW', iata: 'ATW', name: 'Appleton International Airport', city: 'Appleton', state: 'WI', type: 'Regional', lat: 44.2581, lon: -88.5191 },
  { icao: 'KOSH', iata: 'OSH', name: 'Wittman Regional Airport', city: 'Oshkosh', state: 'WI', type: 'Regional', lat: 43.9844, lon: -88.5570 },
  { icao: 'KCWA', iata: 'CWA', name: 'Central Wisconsin Airport', city: 'Mosinee', state: 'WI', type: 'Regional', lat: 44.7776, lon: -89.6668 },
  { icao: 'KLSE', iata: 'LSE', name: 'La Crosse Regional Airport', city: 'La Crosse', state: 'WI', type: 'Regional', lat: 43.8793, lon: -91.2566 },
  { icao: 'KDLH', iata: 'DLH', name: 'Duluth International Airport', city: 'Duluth', state: 'MN', type: 'International', lat: 46.8421, lon: -92.1936 },
  { icao: 'KRST', iata: 'RST', name: 'Rochester International Airport', city: 'Rochester', state: 'MN', type: 'Regional', lat: 43.9083, lon: -92.5000 },
  { icao: 'KPIA', iata: 'PIA', name: 'General Wayne A. Downing Peoria International Airport', city: 'Peoria', state: 'IL', type: 'Regional', lat: 40.6642, lon: -89.6933 },
  { icao: 'KSPI', iata: 'SPI', name: 'Abraham Lincoln Capital Airport', city: 'Springfield', state: 'IL', type: 'Regional', lat: 39.8441, lon: -89.6779 },
  { icao: 'KBMI', iata: 'BMI', name: 'Central Illinois Regional Airport', city: 'Bloomington', state: 'IL', type: 'Regional', lat: 40.4771, lon: -88.9159 },
  { icao: 'KMLI', iata: 'MLI', name: 'Quad City International Airport', city: 'Moline', state: 'IL', type: 'International', lat: 41.4485, lon: -90.5075 },
  { icao: 'KSBN', iata: 'SBN', name: 'South Bend International Airport', city: 'South Bend', state: 'IN', type: 'International', lat: 41.7087, lon: -86.3173 },
  { icao: 'KFWA', iata: 'FWA', name: 'Fort Wayne International Airport', city: 'Fort Wayne', state: 'IN', type: 'International', lat: 40.9785, lon: -85.1951 },
  { icao: 'KEVV', iata: 'EVV', name: 'Evansville Regional Airport', city: 'Evansville', state: 'IN', type: 'Regional', lat: 38.0370, lon: -87.5324 },
  { icao: 'KCID', iata: 'CID', name: 'Eastern Iowa Airport', city: 'Cedar Rapids', state: 'IA', type: 'Regional', lat: 41.8847, lon: -91.7108 },
  { icao: 'KFNT', iata: 'FNT', name: 'Bishop International Airport', city: 'Flint', state: 'MI', type: 'Regional', lat: 42.9654, lon: -83.7436 },
  { icao: 'KLAN', iata: 'LAN', name: 'Capital Region International Airport', city: 'Lansing', state: 'MI', type: 'Regional', lat: 42.7787, lon: -84.5874 },
  { icao: 'KAZO', iata: 'AZO', name: 'Kalamazoo/Battle Creek International Airport', city: 'Kalamazoo', state: 'MI', type: 'Regional', lat: 42.2349, lon: -85.5521 },
  { icao: 'KSGF', iata: 'SGF', name: 'Springfield-Branson National Airport', city: 'Springfield', state: 'MO', type: 'Regional', lat: 37.2457, lon: -93.3886 },
  { icao: 'KLNK', iata: 'LNK', name: 'Lincoln Airport', city: 'Lincoln', state: 'NE', type: 'Regional', lat: 40.8510, lon: -96.7592 },
  // === SOUTH / GULF COAST ===
  { icao: 'KMOB', iata: 'MOB', name: 'Mobile Regional Airport', city: 'Mobile', state: 'AL', type: 'Regional', lat: 30.6912, lon: -88.2428 },
  { icao: 'KMGM', iata: 'MGM', name: 'Montgomery Regional Airport', city: 'Montgomery', state: 'AL', type: 'Regional', lat: 32.3006, lon: -86.3940 },
  { icao: 'KGPT', iata: 'GPT', name: 'Gulfport-Biloxi International Airport', city: 'Gulfport', state: 'MS', type: 'International', lat: 30.4073, lon: -89.0701 },
  { icao: 'KJAN', iata: 'JAN', name: 'Jackson-Medgar Wiley Evers International Airport', city: 'Jackson', state: 'MS', type: 'International', lat: 32.3112, lon: -90.0759 },
  { icao: 'KSHV', iata: 'SHV', name: 'Shreveport Regional Airport', city: 'Shreveport', state: 'LA', type: 'Regional', lat: 32.4466, lon: -93.8256 },
  { icao: 'KLFT', iata: 'LFT', name: 'Lafayette Regional Airport', city: 'Lafayette', state: 'LA', type: 'Regional', lat: 30.2053, lon: -91.9876 },
  { icao: 'KBTR', iata: 'BTR', name: 'Baton Rouge Metropolitan Airport', city: 'Baton Rouge', state: 'LA', type: 'Regional', lat: 30.5332, lon: -91.1496 },
  { icao: 'KXNA', iata: 'XNA', name: 'Northwest Arkansas National Airport', city: 'Fayetteville', state: 'AR', type: 'Regional', lat: 36.2819, lon: -94.3068 },
  { icao: 'KFSM', iata: 'FSM', name: 'Fort Smith Regional Airport', city: 'Fort Smith', state: 'AR', type: 'Regional', lat: 35.3366, lon: -94.3674 },
  // === TEXAS REGIONAL ===
  { icao: 'KLBB', iata: 'LBB', name: 'Lubbock Preston Smith International Airport', city: 'Lubbock', state: 'TX', type: 'International', lat: 33.6636, lon: -101.8229 },
  { icao: 'KAMA', iata: 'AMA', name: 'Rick Husband Amarillo International Airport', city: 'Amarillo', state: 'TX', type: 'International', lat: 35.2194, lon: -101.7059 },
  { icao: 'KMAF', iata: 'MAF', name: 'Midland International Air and Space Port', city: 'Midland', state: 'TX', type: 'International', lat: 31.9425, lon: -102.2019 },
  { icao: 'KCRP', iata: 'CRP', name: 'Corpus Christi International Airport', city: 'Corpus Christi', state: 'TX', type: 'International', lat: 27.7704, lon: -97.5012 },
  { icao: 'KGKY', iata: 'GKY', name: 'Arlington Municipal Airport', city: 'Arlington', state: 'TX', type: 'General Aviation', lat: 32.6639, lon: -97.0943 },
  { icao: 'KTKI', iata: 'TKI', name: 'McKinney National Airport', city: 'McKinney', state: 'TX', type: 'General Aviation', lat: 33.1779, lon: -96.5905 },
  { icao: 'KDWH', iata: 'DWH', name: 'David Wayne Hooks Memorial Airport', city: 'Spring', state: 'TX', type: 'General Aviation', lat: 30.0618, lon: -95.5528 },
  { icao: 'KACT', iata: 'ACT', name: 'Waco Regional Airport', city: 'Waco', state: 'TX', type: 'Regional', lat: 31.6113, lon: -97.2305 },
  { icao: 'KCLL', iata: 'CLL', name: 'Easterwood Airport', city: 'College Station', state: 'TX', type: 'Regional', lat: 30.5886, lon: -96.3638 },
  { icao: 'KTYR', iata: 'TYR', name: 'Tyler Pounds Regional Airport', city: 'Tyler', state: 'TX', type: 'Regional', lat: 32.3541, lon: -95.4024 },
  { icao: 'KBRO', iata: 'BRO', name: 'South Padre Island International Airport', city: 'Brownsville', state: 'TX', type: 'International', lat: 25.9068, lon: -97.4259 },
  { icao: 'KMFE', iata: 'MFE', name: 'McAllen Miller International Airport', city: 'McAllen', state: 'TX', type: 'International', lat: 26.1758, lon: -98.2386 },
  { icao: 'KLRD', iata: 'LRD', name: 'Laredo International Airport', city: 'Laredo', state: 'TX', type: 'International', lat: 27.5437, lon: -99.4617 },
  { icao: 'KABI', iata: 'ABI', name: 'Abilene Regional Airport', city: 'Abilene', state: 'TX', type: 'Regional', lat: 32.4113, lon: -99.6819 },
  // === NORTHEAST ADDITIONAL ===
  { icao: 'KACY', iata: 'ACY', name: 'Atlantic City International Airport', city: 'Atlantic City', state: 'NJ', type: 'International', lat: 39.4576, lon: -74.5772 },
  { icao: 'KTTN', iata: 'TTN', name: 'Trenton-Mercer Airport', city: 'Trenton', state: 'NJ', type: 'Regional', lat: 40.2767, lon: -74.8135 },
  { icao: 'KCDW', iata: 'CDW', name: 'Essex County Airport', city: 'Caldwell', state: 'NJ', type: 'General Aviation', lat: 40.8752, lon: -74.2814 },
  { icao: 'KISP', iata: 'ISP', name: 'Long Island MacArthur Airport', city: 'Islip', state: 'NY', type: 'Regional', lat: 40.7952, lon: -73.1002 },
  { icao: 'KSWF', iata: 'SWF', name: 'New York Stewart International Airport', city: 'Newburgh', state: 'NY', type: 'Regional', lat: 41.5041, lon: -74.1048 },
  { icao: 'KROC', iata: 'ROC', name: 'Greater Rochester International Airport', city: 'Rochester', state: 'NY', type: 'International', lat: 43.1189, lon: -77.6724 },
  { icao: 'KITH', iata: 'ITH', name: 'Ithaca Tompkins International Airport', city: 'Ithaca', state: 'NY', type: 'Regional', lat: 42.4913, lon: -76.4584 },
  { icao: 'KELM', iata: 'ELM', name: 'Elmira/Corning Regional Airport', city: 'Elmira', state: 'NY', type: 'Regional', lat: 42.1599, lon: -76.8916 },
  { icao: 'KABE', iata: 'ABE', name: 'Lehigh Valley International Airport', city: 'Allentown', state: 'PA', type: 'International', lat: 40.6521, lon: -75.4408 },
  { icao: 'KAVP', iata: 'AVP', name: 'Wilkes-Barre/Scranton International Airport', city: 'Wilkes-Barre', state: 'PA', type: 'International', lat: 41.3385, lon: -75.7234 },
  { icao: 'KMDT', iata: 'MDT', name: 'Harrisburg International Airport', city: 'Harrisburg', state: 'PA', type: 'International', lat: 40.1935, lon: -76.7634 },
  { icao: 'KERI', iata: 'ERI', name: 'Erie International Airport', city: 'Erie', state: 'PA', type: 'International', lat: 42.0831, lon: -80.1739 },
  { icao: 'KPNE', iata: 'PNE', name: 'Northeast Philadelphia Airport', city: 'Philadelphia', state: 'PA', type: 'General Aviation', lat: 40.0819, lon: -75.0106 },
  { icao: 'KILG', iata: 'ILG', name: 'Wilmington Airport', city: 'Wilmington', state: 'DE', type: 'Regional', lat: 39.6787, lon: -75.6065 },
  { icao: 'KBDL', iata: 'BDL', name: 'Bradley International Airport', city: 'Hartford', state: 'CT', type: 'International', lat: 41.9389, lon: -72.6832 },
  { icao: 'KHVN', iata: 'HVN', name: 'Tweed-New Haven Airport', city: 'New Haven', state: 'CT', type: 'Regional', lat: 41.2637, lon: -72.8868 },
  { icao: 'KOXC', iata: 'OXC', name: 'Waterbury-Oxford Airport', city: 'Oxford', state: 'CT', type: 'General Aviation', lat: 41.4786, lon: -73.1352 },
  { icao: 'KMVY', iata: 'MVY', name: "Martha's Vineyard Airport", city: "Martha's Vineyard", state: 'MA', type: 'Regional', lat: 41.3935, lon: -70.6143 },
  { icao: 'KACK', iata: 'ACK', name: 'Nantucket Memorial Airport', city: 'Nantucket', state: 'MA', type: 'Regional', lat: 41.2531, lon: -70.0604 },
  { icao: 'KHYA', iata: 'HYA', name: 'Barnstable Municipal Airport', city: 'Hyannis', state: 'MA', type: 'Regional', lat: 41.6693, lon: -70.2804 },
  { icao: 'KORH', iata: 'ORH', name: 'Worcester Regional Airport', city: 'Worcester', state: 'MA', type: 'Regional', lat: 42.2673, lon: -71.8757 },
  { icao: 'KLEB', iata: 'LEB', name: 'Lebanon Municipal Airport', city: 'Lebanon', state: 'NH', type: 'Regional', lat: 43.6261, lon: -72.3042 },
  { icao: 'KPSM', iata: 'PSM', name: 'Portsmouth International Airport at Pease', city: 'Portsmouth', state: 'NH', type: 'Regional', lat: 43.0779, lon: -70.8233 },
  { icao: 'KBHB', iata: 'BHB', name: 'Hancock County-Bar Harbor Airport', city: 'Bar Harbor', state: 'ME', type: 'Regional', lat: 44.4498, lon: -68.3616 },
  { icao: 'KRKD', iata: 'RKD', name: 'Knox County Regional Airport', city: 'Rockland', state: 'ME', type: 'Regional', lat: 44.0601, lon: -69.0993 },
  // === SOUTHEAST ADDITIONAL ===
  { icao: 'KCAE', iata: 'CAE', name: 'Columbia Metropolitan Airport', city: 'Columbia', state: 'SC', type: 'Regional', lat: 33.9388, lon: -81.1195 },
  { icao: 'KAGS', iata: 'AGS', name: 'Augusta Regional Airport', city: 'Augusta', state: 'GA', type: 'Regional', lat: 33.3700, lon: -81.9645 },
  { icao: 'KFTY', iata: 'FTY', name: 'Fulton County Airport-Brown Field', city: 'Atlanta', state: 'GA', type: 'Executive', lat: 33.7791, lon: -84.5214 },
  { icao: 'KRYY', iata: 'RYY', name: 'Cobb County International Airport-McCollum Field', city: 'Kennesaw', state: 'GA', type: 'General Aviation', lat: 34.0132, lon: -84.5971 },
  { icao: 'KMCN', iata: 'MCN', name: 'Middle Georgia Regional Airport', city: 'Macon', state: 'GA', type: 'Regional', lat: 32.6928, lon: -83.6492 },
  { icao: 'KCHA', iata: 'CHA', name: 'Chattanooga Metropolitan Airport', city: 'Chattanooga', state: 'TN', type: 'Regional', lat: 35.0353, lon: -85.2038 },
  { icao: 'KTRI', iata: 'TRI', name: 'Tri-Cities Airport', city: 'Blountville', state: 'TN', type: 'Regional', lat: 36.4752, lon: -82.4074 },
  { icao: 'KILM', iata: 'ILM', name: 'Wilmington International Airport', city: 'Wilmington', state: 'NC', type: 'International', lat: 34.2706, lon: -77.9026 },
  { icao: 'KAVL', iata: 'AVL', name: 'Asheville Regional Airport', city: 'Asheville', state: 'NC', type: 'Regional', lat: 35.4362, lon: -82.5418 },
  { icao: 'KFAY', iata: 'FAY', name: 'Fayetteville Regional Airport', city: 'Fayetteville', state: 'NC', type: 'Regional', lat: 34.9912, lon: -78.8803 },
  { icao: 'KPHF', iata: 'PHF', name: 'Newport News/Williamsburg International Airport', city: 'Newport News', state: 'VA', type: 'International', lat: 37.1319, lon: -76.4930 },
  { icao: 'KROA', iata: 'ROA', name: 'Roanoke-Blacksburg Regional Airport', city: 'Roanoke', state: 'VA', type: 'Regional', lat: 37.3255, lon: -79.9754 },
  { icao: 'KCHO', iata: 'CHO', name: 'Charlottesville-Albemarle Airport', city: 'Charlottesville', state: 'VA', type: 'Regional', lat: 38.1386, lon: -78.4529 },
  { icao: 'KCRW', iata: 'CRW', name: 'Yeager Airport', city: 'Charleston', state: 'WV', type: 'Regional', lat: 38.3731, lon: -81.5932 },
  { icao: 'KSBY', iata: 'SBY', name: 'Salisbury-Ocean City Wicomico Regional Airport', city: 'Salisbury', state: 'MD', type: 'Regional', lat: 38.3405, lon: -75.5103 },
  // === VIRGINIA/NC ADDITIONAL ===
  { icao: 'KGAI', iata: 'GAI', name: 'Montgomery County Airpark', city: 'Gaithersburg', state: 'MD', type: 'General Aviation', lat: 39.1683, lon: -77.1660 },
  { icao: 'KFDK', iata: 'FDK', name: 'Frederick Municipal Airport', city: 'Frederick', state: 'MD', type: 'General Aviation', lat: 39.4176, lon: -77.3743 },
  { icao: 'KESN', iata: 'ESN', name: 'Easton Airport', city: 'Easton', state: 'MD', type: 'General Aviation', lat: 38.8042, lon: -76.0690 },
  // === KENTUCKY / TENNESSEE ADDITIONAL ===
  { icao: 'KBWG', iata: 'BWG', name: 'Bowling Green-Warren County Regional Airport', city: 'Bowling Green', state: 'KY', type: 'Regional', lat: 36.9645, lon: -86.4197 },
  { icao: 'KPAH', iata: 'PAH', name: 'Barkley Regional Airport', city: 'Paducah', state: 'KY', type: 'Regional', lat: 37.0603, lon: -88.7738 },
  // === HAWAII / ALASKA ===
  { icao: 'PHOG', iata: 'OGG', name: 'Kahului Airport', city: 'Kahului', state: 'HI', type: 'International', lat: 20.8986, lon: -156.4305 },
  { icao: 'PHKO', iata: 'KOA', name: 'Ellison Onizuka Kona International Airport', city: 'Kailua-Kona', state: 'HI', type: 'International', lat: 19.7388, lon: -156.0456 },
  { icao: 'PHLI', iata: 'LIH', name: 'Lihue Airport', city: 'Lihue', state: 'HI', type: 'Regional', lat: 21.9760, lon: -159.3390 },
  { icao: 'PAFA', iata: 'FAI', name: 'Fairbanks International Airport', city: 'Fairbanks', state: 'AK', type: 'International', lat: 64.8151, lon: -147.8561 },
  { icao: 'PAJN', iata: 'JNU', name: 'Juneau International Airport', city: 'Juneau', state: 'AK', type: 'International', lat: 58.3550, lon: -134.5762 },
  // === ADDITIONAL INDIANA ===
  { icao: 'KMQJ', iata: 'MQJ', name: 'Indianapolis Regional Airport', city: 'Greenfield', state: 'IN', type: 'General Aviation', lat: 39.8441, lon: -85.9011 },
  // === ADDITIONAL KANSAS/OKLAHOMA/NM ===
  { icao: 'KMHK', iata: 'MHK', name: 'Manhattan Regional Airport', city: 'Manhattan', state: 'KS', type: 'Regional', lat: 39.1410, lon: -96.6708 },
  { icao: 'KPWA', iata: 'PWA', name: 'Wiley Post Airport', city: 'Oklahoma City', state: 'OK', type: 'General Aviation', lat: 35.5342, lon: -97.6471 },
  { icao: 'KSWO', iata: 'SWO', name: 'Stillwater Regional Airport', city: 'Stillwater', state: 'OK', type: 'Regional', lat: 36.1612, lon: -97.0857 },
  { icao: 'KSAF', iata: 'SAF', name: 'Santa Fe Municipal Airport', city: 'Santa Fe', state: 'NM', type: 'Regional', lat: 35.6171, lon: -106.0892 },
  // === MISC REMAINING ===
  { icao: 'KHXD', iata: 'HHH', name: 'Hilton Head Airport', city: 'Hilton Head Island', state: 'SC', type: 'Regional', lat: 32.2244, lon: -80.6975 },
  { icao: 'KBQK', iata: 'BQK', name: 'Brunswick Golden Isles Airport', city: 'Brunswick', state: 'GA', type: 'Regional', lat: 31.2588, lon: -81.4665 },
  { icao: 'KUGN', iata: 'UGN', name: 'Waukegan National Airport', city: 'Waukegan', state: 'IL', type: 'General Aviation', lat: 42.4222, lon: -87.8679 },
  { icao: 'KANE', iata: 'ANE', name: 'Anoka County-Blaine Airport', city: 'Blaine', state: 'MN', type: 'General Aviation', lat: 45.1450, lon: -93.2114 },
  { icao: 'KLUK', iata: 'LUK', name: 'Cincinnati Municipal Airport - Lunken Field', city: 'Cincinnati', state: 'OH', type: 'General Aviation', lat: 39.1033, lon: -84.4186 },
  { icao: 'KRNT', iata: 'RNT', name: 'Renton Municipal Airport', city: 'Renton', state: 'WA', type: 'General Aviation', lat: 47.4931, lon: -122.2159 },
  { icao: 'KTIW', iata: 'TIW', name: 'Tacoma Narrows Airport', city: 'Tacoma', state: 'WA', type: 'General Aviation', lat: 47.2679, lon: -122.5781 },
  { icao: 'KTTD', iata: 'TTD', name: 'Portland-Troutdale Airport', city: 'Troutdale', state: 'OR', type: 'General Aviation', lat: 45.5494, lon: -122.4013 },
  { icao: 'KFNL', iata: 'FNL', name: 'Northern Colorado Regional Airport', city: 'Fort Collins', state: 'CO', type: 'General Aviation', lat: 40.4518, lon: -105.0113 },
  { icao: 'KGLS', iata: 'GLS', name: 'Scholes International Airport', city: 'Galveston', state: 'TX', type: 'Regional', lat: 29.2653, lon: -94.8604 },
  { icao: 'KVLD', iata: 'VLD', name: 'Valdosta Regional Airport', city: 'Valdosta', state: 'GA', type: 'Regional', lat: 30.7825, lon: -83.2767 },
  { icao: 'KCSG', iata: 'CSG', name: 'Columbus Metropolitan Airport', city: 'Columbus', state: 'GA', type: 'Regional', lat: 32.5163, lon: -84.9389 },
  { icao: 'KSUX', iata: 'SUX', name: 'Sioux Gateway Airport', city: 'Sioux City', state: 'IA', type: 'Regional', lat: 42.4026, lon: -96.3844 },
  { icao: 'KALO', iata: 'ALO', name: 'Waterloo Regional Airport', city: 'Waterloo', state: 'IA', type: 'Regional', lat: 42.5571, lon: -92.4003 },
  { icao: 'KDBQ', iata: 'DBQ', name: 'Dubuque Regional Airport', city: 'Dubuque', state: 'IA', type: 'Regional', lat: 42.4020, lon: -90.7095 },
  { icao: 'KDHN', iata: 'DHN', name: 'Dothan Regional Airport', city: 'Dothan', state: 'AL', type: 'Regional', lat: 31.3213, lon: -85.4496 },
  { icao: 'KAEX', iata: 'AEX', name: 'Alexandria International Airport', city: 'Alexandria', state: 'LA', type: 'Regional', lat: 31.3274, lon: -92.5486 },
  { icao: 'KPIB', iata: 'PIB', name: 'Hattiesburg-Laurel Regional Airport', city: 'Hattiesburg', state: 'MS', type: 'Regional', lat: 31.4671, lon: -89.3371 },
  { icao: 'KTUP', iata: 'TUP', name: 'Tupelo Regional Airport', city: 'Tupelo', state: 'MS', type: 'Regional', lat: 34.2681, lon: -88.7699 },
  { icao: 'KCMH', iata: 'CMH', name: 'John Glenn Columbus International Airport', city: 'Columbus', state: 'OH', type: 'International', lat: 39.9980, lon: -82.8919 },
  { icao: 'KBGM', iata: 'BGM', name: 'Greater Binghamton Airport', city: 'Binghamton', state: 'NY', type: 'Regional', lat: 42.2087, lon: -75.9798 },
  { icao: 'KUNV', iata: 'UNV', name: 'University Park Airport', city: 'State College', state: 'PA', type: 'Regional', lat: 40.8493, lon: -77.8487 },
  { icao: 'KFFC', iata: 'FFC', name: 'Peachtree City-Falcon Field', city: 'Peachtree City', state: 'GA', type: 'General Aviation', lat: 33.3573, lon: -84.5718 },
  { icao: 'KLZU', iata: 'LZU', name: 'Gwinnett County Airport-Briscoe Field', city: 'Lawrenceville', state: 'GA', type: 'General Aviation', lat: 33.9781, lon: -83.9624 },
  { icao: 'KSSI', iata: 'SSI', name: 'Malcolm McKinnon Airport', city: 'St. Simons Island', state: 'GA', type: 'General Aviation', lat: 31.1518, lon: -81.3913 },
  { icao: 'KEAU', iata: 'EAU', name: 'Chippewa Valley Regional Airport', city: 'Eau Claire', state: 'WI', type: 'Regional', lat: 44.8658, lon: -91.4843 },
  { icao: 'KMKL', iata: 'MKL', name: 'McKellar-Sipes Regional Airport', city: 'Jackson', state: 'TN', type: 'Regional', lat: 35.5999, lon: -88.9156 },
  { icao: 'KINT', iata: 'INT', name: 'Smith Reynolds Airport', city: 'Winston-Salem', state: 'NC', type: 'General Aviation', lat: 36.1337, lon: -80.2220 },
  { icao: 'KOAJ', iata: 'OAJ', name: 'Albert J. Ellis Airport', city: 'Jacksonville', state: 'NC', type: 'Regional', lat: 34.8292, lon: -77.6121 },
  { icao: 'KLYH', iata: 'LYH', name: 'Lynchburg Regional Airport', city: 'Lynchburg', state: 'VA', type: 'Regional', lat: 37.3267, lon: -79.2004 },
  { icao: 'KCKB', iata: 'CKB', name: 'North Central West Virginia Airport', city: 'Clarksburg', state: 'WV', type: 'Regional', lat: 39.2966, lon: -80.2281 },
  { icao: 'KMGW', iata: 'MGW', name: 'Morgantown Municipal Airport', city: 'Morgantown', state: 'WV', type: 'Regional', lat: 39.6429, lon: -79.9164 },
  { icao: 'KFLO', iata: 'FLO', name: 'Florence Regional Airport', city: 'Florence', state: 'SC', type: 'Regional', lat: 34.1854, lon: -79.7239 },
  { icao: 'KSFZ', iata: 'SFZ', name: 'North Central State Airport', city: 'Pawtucket', state: 'RI', type: 'General Aviation', lat: 41.9208, lon: -71.4914 },
  { icao: 'KGON', iata: 'GON', name: 'Groton-New London Airport', city: 'Groton', state: 'CT', type: 'Regional', lat: 41.3301, lon: -72.0451 },
  { icao: 'KHFD', iata: 'HFD', name: 'Hartford-Brainard Airport', city: 'Hartford', state: 'CT', type: 'General Aviation', lat: 41.7367, lon: -72.6494 },
  { icao: 'KBTM', iata: 'BTM', name: 'Bert Mooney Airport', city: 'Butte', state: 'MT', type: 'Regional', lat: 45.9548, lon: -112.4972 },
  { icao: 'KCOD', iata: 'COD', name: 'Yellowstone Regional Airport', city: 'Cody', state: 'WY', type: 'Regional', lat: 44.5202, lon: -109.0238 },
  { icao: 'KRIW', iata: 'RIW', name: 'Riverton Regional Airport', city: 'Riverton', state: 'WY', type: 'Regional', lat: 43.0642, lon: -108.4598 },
  { icao: 'KLAR', iata: 'LAR', name: 'Laramie Regional Airport', city: 'Laramie', state: 'WY', type: 'Regional', lat: 41.3121, lon: -105.6750 },
  { icao: 'KSHR', iata: 'SHR', name: 'Sheridan County Airport', city: 'Sheridan', state: 'WY', type: 'Regional', lat: 44.7692, lon: -106.9803 },
  { icao: 'KABR', iata: 'ABR', name: 'Aberdeen Regional Airport', city: 'Aberdeen', state: 'SD', type: 'Regional', lat: 45.4491, lon: -98.4218 },
  { icao: 'KGRI', iata: 'GRI', name: 'Central Nebraska Regional Airport', city: 'Grand Island', state: 'NE', type: 'Regional', lat: 40.9675, lon: -98.3096 },
  { icao: 'PADQ', iata: 'ADQ', name: 'Kodiak Airport', city: 'Kodiak', state: 'AK', type: 'Regional', lat: 57.7500, lon: -152.4938 },
  { icao: 'KROW', iata: 'ROW', name: 'Roswell International Air Center', city: 'Roswell', state: 'NM', type: 'Regional', lat: 33.3016, lon: -104.5307 },
  { icao: 'KLRU', iata: 'LRU', name: 'Las Cruces International Airport', city: 'Las Cruces', state: 'NM', type: 'Regional', lat: 32.2894, lon: -106.9220 },
  { icao: 'KCDC', iata: 'CDC', name: 'Cedar City Regional Airport', city: 'Cedar City', state: 'UT', type: 'Regional', lat: 37.7010, lon: -113.0986 },
  { icao: 'KLAW', iata: 'LAW', name: 'Lawton-Fort Sill Regional Airport', city: 'Lawton', state: 'OK', type: 'Regional', lat: 34.5677, lon: -98.4166 },
  { icao: 'KTXK', iata: 'TXK', name: 'Texarkana Regional Airport', city: 'Texarkana', state: 'AR', type: 'Regional', lat: 33.4537, lon: -93.9910 },
  { icao: 'KJBR', iata: 'JBR', name: 'Jonesboro Municipal Airport', city: 'Jonesboro', state: 'AR', type: 'Regional', lat: 35.8318, lon: -90.6465 },
  { icao: 'KOWB', iata: 'OWB', name: 'Owensboro-Daviess County Airport', city: 'Owensboro', state: 'KY', type: 'Regional', lat: 37.7401, lon: -87.1668 },
  { icao: 'KGLH', iata: 'GLH', name: 'Mid Delta Regional Airport', city: 'Greenville', state: 'MS', type: 'Regional', lat: 33.4829, lon: -90.9856 },
  { icao: 'KBPT', iata: 'BPT', name: 'Jack Brooks Regional Airport', city: 'Beaumont', state: 'TX', type: 'Regional', lat: 29.9508, lon: -94.0207 },
  { icao: 'KSPS', iata: 'SPS', name: 'Wichita Falls Municipal Airport', city: 'Wichita Falls', state: 'TX', type: 'Regional', lat: 33.9888, lon: -98.4919 },
  { icao: 'KSJT', iata: 'SJT', name: 'San Angelo Regional Airport', city: 'San Angelo', state: 'TX', type: 'Regional', lat: 31.3577, lon: -100.4963 },
  { icao: 'KSSF', iata: 'SSF', name: 'Stinson Municipal Airport', city: 'San Antonio', state: 'TX', type: 'General Aviation', lat: 29.3370, lon: -98.4711 },
  { icao: 'KGTU', iata: 'GTU', name: 'Georgetown Municipal Airport', city: 'Georgetown', state: 'TX', type: 'General Aviation', lat: 30.6788, lon: -97.6794 },
  { icao: 'KRAL', iata: 'RAL', name: 'Riverside Municipal Airport', city: 'Riverside', state: 'CA', type: 'General Aviation', lat: 33.9519, lon: -117.4451 },
  { icao: 'KWHP', iata: 'WHP', name: 'Whiteman Airport', city: 'Pacoima', state: 'CA', type: 'General Aviation', lat: 34.2593, lon: -118.4134 },
  { icao: 'KSCK', iata: 'SCK', name: 'Stockton Metropolitan Airport', city: 'Stockton', state: 'CA', type: 'Regional', lat: 37.8942, lon: -121.2386 },
  { icao: 'KRHV', iata: 'RHV', name: 'Reid-Hillview Airport', city: 'San Jose', state: 'CA', type: 'General Aviation', lat: 37.3329, lon: -121.8189 },
  { icao: 'KOTH', iata: 'OTH', name: 'Southwest Oregon Regional Airport', city: 'North Bend', state: 'OR', type: 'Regional', lat: 43.4171, lon: -124.2460 },
  { icao: 'KARR', iata: 'ARR', name: 'Aurora Municipal Airport', city: 'Aurora', state: 'IL', type: 'General Aviation', lat: 41.7719, lon: -88.4757 },
  { icao: 'KCMI', iata: 'CMI', name: 'University of Illinois Willard Airport', city: 'Champaign', state: 'IL', type: 'Regional', lat: 40.0392, lon: -88.2781 },
  { icao: 'KLBF', iata: 'LBF', name: 'North Platte Regional Airport', city: 'North Platte', state: 'NE', type: 'Regional', lat: 41.1262, lon: -100.6836 },
  { icao: 'KEAR', iata: 'EAR', name: 'Kearney Regional Airport', city: 'Kearney', state: 'NE', type: 'Regional', lat: 40.7270, lon: -99.0068 },
  { icao: 'KGCK', iata: 'GCK', name: 'Garden City Regional Airport', city: 'Garden City', state: 'KS', type: 'Regional', lat: 37.9275, lon: -100.7244 },
  { icao: 'KLEE', iata: 'LEE', name: 'Leesburg International Airport', city: 'Leesburg', state: 'FL', type: 'General Aviation', lat: 28.8234, lon: -81.8093 },
  { icao: 'KVQQ', iata: 'VQQ', name: 'Cecil Airport', city: 'Jacksonville', state: 'FL', type: 'General Aviation', lat: 30.2187, lon: -81.8767 },
  { icao: 'KLNS', iata: 'LNS', name: 'Lancaster Airport', city: 'Lancaster', state: 'PA', type: 'General Aviation', lat: 40.1217, lon: -76.2961 },
  { icao: 'KIPT', iata: 'IPT', name: 'Williamsport Regional Airport', city: 'Williamsport', state: 'PA', type: 'Regional', lat: 41.2418, lon: -76.9211 },
  { icao: 'KPVC', iata: 'PVC', name: 'Provincetown Municipal Airport', city: 'Provincetown', state: 'MA', type: 'Regional', lat: 42.0719, lon: -70.2214 },
  { icao: 'KAST', iata: 'AST', name: 'Astoria Regional Airport', city: 'Astoria', state: 'OR', type: 'Regional', lat: 46.1580, lon: -123.8787 },
];

// Deduplicate by ICAO code (keep first occurrence)
const seen = new Set();
const deduped = [];
for (const a of US_AIRPORTS) {
  if (!seen.has(a.icao)) {
    seen.add(a.icao);
    deduped.push(a);
  }
}

// Quick lookup by ICAO code
export const AIRPORT_MAP = Object.fromEntries(deduped.map(a => [a.icao, a]));

// Get all unique states represented
export const AIRPORT_STATES = [...new Set(deduped.map(a => a.state))].sort();

// Re-export deduplicated as the default list
export { deduped as AIRPORTS_DEDUPED };
